"""``LlmTtaDfsConfig`` constructor mapping for the submit stage."""

from typing import Optional

from layers.layer_1_competition.level_1_impl.level_arc_agi_2.level_0 import (
    LlmTtaDfsConfig,
)


def build_llm_tta_config(
    *,
    llm_execution_mode: str = "surrogate",
    llm_num_augmentations: int = 8,
    llm_beam_width: int = 12,
    llm_max_candidates: int = 6,
    llm_max_neg_log_score: float = 120.0,
    llm_seed: int = 0,
    llm_consistency_weight: float = 1.0,
    llm_model_weight: float = 1.0,
    llm_augmentation_likelihood_weight: float = 1.0,
    llm_enable_neural_backend: bool = False,
    llm_model_path: Optional[str] = None,
    llm_lora_path: Optional[str] = None,
    llm_max_runtime_sec: float = 0.0,
    llm_task_runtime_sec: float = 0.0,
    llm_decode_runtime_sec: float = 0.0,
    llm_adapt_steps: int = 0,
    llm_adapt_batch_size: int = 1,
    llm_adapt_gradient_accumulation_steps: int = 1,
    llm_adapt_disabled: bool = False,
    llm_per_task_adaptation: bool = False,
    llm_runtime_attention_mode: str = "auto",
    llm_runtime_disable_compile: bool = False,
    llm_runtime_allocator_expandable_segments: bool = True,
    llm_runtime_allocator_max_split_size_mb: int = 0,
    llm_prefer_cnn_attempt1: bool = False,
    llm_candidate_ranker: str = "default",
    llm_infer_artifact_dir: Optional[str] = None,
    llm_infer_artifact_run_name: str = "",
) -> LlmTtaDfsConfig:
    return LlmTtaDfsConfig(
        execution_mode=str(llm_execution_mode or "surrogate"),
        num_augmentations=int(llm_num_augmentations or 1),
        beam_width=int(llm_beam_width or 1),
        max_candidates=int(llm_max_candidates or 1),
        max_neg_log_score=float(llm_max_neg_log_score or 120.0),
        seed=int(llm_seed or 0),
        consistency_weight=float(llm_consistency_weight),
        model_weight=float(llm_model_weight),
        augmentation_likelihood_weight=float(llm_augmentation_likelihood_weight),
        enable_neural_backend=bool(llm_enable_neural_backend),
        model_path=(str(llm_model_path).strip() if llm_model_path else None),
        lora_path=(str(llm_lora_path).strip() if llm_lora_path else None),
        max_runtime_sec=float(llm_max_runtime_sec or 0.0),
        task_runtime_sec=float(llm_task_runtime_sec or 0.0),
        decode_runtime_sec=float(llm_decode_runtime_sec or 0.0),
        adapt_steps=int(llm_adapt_steps or 0),
        adapt_batch_size=max(1, int(llm_adapt_batch_size or 1)),
        adapt_gradient_accumulation_steps=max(1, int(llm_adapt_gradient_accumulation_steps or 1)),
        adapt_disabled=bool(llm_adapt_disabled),
        per_task_adaptation=bool(llm_per_task_adaptation),
        runtime_attention_mode=str(llm_runtime_attention_mode or "auto"),
        runtime_disable_compile=bool(llm_runtime_disable_compile),
        runtime_allocator_expandable_segments=bool(llm_runtime_allocator_expandable_segments),
        runtime_allocator_max_split_size_mb=int(llm_runtime_allocator_max_split_size_mb or 0),
        prefer_cnn_attempt1=bool(llm_prefer_cnn_attempt1),
        candidate_ranker=str(llm_candidate_ranker or "default"),
        infer_artifact_dir=(str(llm_infer_artifact_dir).strip() if llm_infer_artifact_dir else None),
        infer_artifact_run_name=str(llm_infer_artifact_run_name or ""),
    )
